// Plain-text usage guide embedded as the "Instructions" tab of the combined
// import workbook. Kept as an ordered list of lines (rather than markdown)
// since it's rendered straight into spreadsheet cells.
export const INSTRUCTIONS_LINES: string[] = [
  "PayrollIN - Setup & Usage Guide",
  "",
  "This one workbook has 4 data tabs (Employee Master, Salary Structure, Investment Declaration, Previous Employer) plus this Instructions tab. Columns marked with * are mandatory.",
  "",
  "TIP: For just ONE employee, you don't need Excel at all - in the app, go to Employees > + Add Employee, then fill in Salary Structure / Investment Declaration / Previous Employer directly on that employee's page. Use this workbook only when adding many employees at once.",
  "",
  "STEP 1 - Fill in your data in this workbook",
  "1. Go to the 'Employee Master' tab. Enter one row per employee. Employee Code is whatever short code you want to use (e.g. EMP101) - you'll reuse it on the other tabs.",
  "2. Go to the 'Salary Structure' tab. Enter each employee's ANNUAL amount for each salary component for the current financial year. Employee Code must match the Employee Master tab exactly.",
  "3. Go to the 'Investment Declaration' tab for employees who have tax-saving investments, medical insurance, home loan interest, or HRA rent to declare. Employee Code must match.",
  "4. Go to the 'Previous Employer' tab ONLY for employees who joined partway through this financial year and have salary/TDS from a previous employer in the same year.",
  "5. Save this file when done.",
  "",
  "STEP 2 - Import this file into the app",
  "6. In the app, open 'Import Wizard' from the left-hand menu.",
  "7. Choose 'Combined Setup Template', click 'Upload & Import', and select this saved file.",
  "8. Check the Import Summary: it shows how many rows were imported and lists any errors with the row number and tab they came from. Fix those rows in this file and re-upload if needed.",
  "9. If you re-upload after only fixing a few rows, you'll see 'already exists' errors for employees that were already imported successfully the first time - that's expected, only the fixed/new rows need to succeed.",
  "",
  "STEP 3 - Process monthly payroll",
  "10. Open 'Payroll Runs' from the left-hand menu.",
  "11. Choose the Financial Year and Payroll Month, then click 'Create / Open Run'.",
  "12. Click 'Run Payroll Calculation'. This works out gross salary, PF/ESI/PT, TDS under BOTH the Old and New tax regimes, and net salary for every employee.",
  "13. Click into any employee's row to see their Old vs New regime comparison, and 'View Calculation' for the full step-by-step tax working.",
  "14. Once you're satisfied with the numbers, move the run forward using the buttons at the top: Reviewed -> Approved -> Locked -> Paid. Once Locked, further changes must go through an audited Manual Adjustment (with a reason and your name recorded) rather than a silent edit.",
  "",
  "STEP 4 - Generate outputs",
  "15. 'Salary Register' - the full month's payroll in one table, exportable to Excel or CSV.",
  "16. 'Bank Payment File' - the list to hand to your bank for salary transfer, with account/IFSC checks and a choice of bank-specific column formats.",
  "17. 'Salary Slips' - open any employee's payslip to view, print, or download as a PDF.",
  "",
  "STEP 5 - Full & Final settlement (F&F) for an employee who is leaving",
  "18. Open the employee's record under 'Employees', click 'Edit Profile', enter their 'Date of Leaving', and save.",
  "19. Create/open the payroll run for their last working month as usual and click 'Run Payroll Calculation'. The app automatically settles their ENTIRE remaining annual TDS in this final month instead of spreading it over the rest of the year.",
  "20. Add any final-settlement items (leave encashment, gratuity, notice-pay recovery, etc.) as a Manual Adjustment on their payroll line, with a reason recorded.",
  "21. Move that run through Reviewed -> Approved -> Locked -> Paid as usual, then include them in that month's Salary Register, Bank Payment File, and Salary Slip.",
  "",
  "Monthly variable pay (optional)",
  "22. For LOP (Loss of Pay) days or one-off pay like bonus/incentive/overtime/arrears in a specific month, use the separate 'Monthly Payroll Input' template from the Import Wizard instead of this workbook.",
];
